/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowGraphIndexRouteImport } from './routes/flow-graph/index'
import { Route as FlowAdvancedIndexRouteImport } from './routes/flow-advanced/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as BoxIndexRouteImport } from './routes/box/index'
import { Route as BoxDiceIndexRouteImport } from './routes/box-dice/index'
import { Route as BoxDiceAdvancedIndexRouteImport } from './routes/box-dice-advanced/index'
import { Route as AutomatedSystemIndexRouteImport } from './routes/automated-system/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowGraphIndexRoute = FlowGraphIndexRouteImport.update({
  id: '/flow-graph/',
  path: '/flow-graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowAdvancedIndexRoute = FlowAdvancedIndexRouteImport.update({
  id: '/flow-advanced/',
  path: '/flow-advanced/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxIndexRoute = BoxIndexRouteImport.update({
  id: '/box/',
  path: '/box/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDiceIndexRoute = BoxDiceIndexRouteImport.update({
  id: '/box-dice/',
  path: '/box-dice/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDiceAdvancedIndexRoute = BoxDiceAdvancedIndexRouteImport.update({
  id: '/box-dice-advanced/',
  path: '/box-dice-advanced/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatedSystemIndexRoute = AutomatedSystemIndexRouteImport.update({
  id: '/automated-system/',
  path: '/automated-system/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/automated-system/': typeof AutomatedSystemIndexRoute
  '/box-dice-advanced/': typeof BoxDiceAdvancedIndexRoute
  '/box-dice/': typeof BoxDiceIndexRoute
  '/box/': typeof BoxIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/flow-advanced/': typeof FlowAdvancedIndexRoute
  '/flow-graph/': typeof FlowGraphIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/automated-system': typeof AutomatedSystemIndexRoute
  '/box-dice-advanced': typeof BoxDiceAdvancedIndexRoute
  '/box-dice': typeof BoxDiceIndexRoute
  '/box': typeof BoxIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/flow-advanced': typeof FlowAdvancedIndexRoute
  '/flow-graph': typeof FlowGraphIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/automated-system/': typeof AutomatedSystemIndexRoute
  '/box-dice-advanced/': typeof BoxDiceAdvancedIndexRoute
  '/box-dice/': typeof BoxDiceIndexRoute
  '/box/': typeof BoxIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/flow-advanced/': typeof FlowAdvancedIndexRoute
  '/flow-graph/': typeof FlowGraphIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/automated-system/'
    | '/box-dice-advanced/'
    | '/box-dice/'
    | '/box/'
    | '/components/'
    | '/flow-advanced/'
    | '/flow-graph/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/automated-system'
    | '/box-dice-advanced'
    | '/box-dice'
    | '/box'
    | '/components'
    | '/flow-advanced'
    | '/flow-graph'
  id:
    | '__root__'
    | '/'
    | '/forbidden'
    | '/login'
    | '/automated-system/'
    | '/box-dice-advanced/'
    | '/box-dice/'
    | '/box/'
    | '/components/'
    | '/flow-advanced/'
    | '/flow-graph/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  AutomatedSystemIndexRoute: typeof AutomatedSystemIndexRoute
  BoxDiceAdvancedIndexRoute: typeof BoxDiceAdvancedIndexRoute
  BoxDiceIndexRoute: typeof BoxDiceIndexRoute
  BoxIndexRoute: typeof BoxIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  FlowAdvancedIndexRoute: typeof FlowAdvancedIndexRoute
  FlowGraphIndexRoute: typeof FlowGraphIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-graph/': {
      id: '/flow-graph/'
      path: '/flow-graph'
      fullPath: '/flow-graph/'
      preLoaderRoute: typeof FlowGraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-advanced/': {
      id: '/flow-advanced/'
      path: '/flow-advanced'
      fullPath: '/flow-advanced/'
      preLoaderRoute: typeof FlowAdvancedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box/': {
      id: '/box/'
      path: '/box'
      fullPath: '/box/'
      preLoaderRoute: typeof BoxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-dice/': {
      id: '/box-dice/'
      path: '/box-dice'
      fullPath: '/box-dice/'
      preLoaderRoute: typeof BoxDiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-dice-advanced/': {
      id: '/box-dice-advanced/'
      path: '/box-dice-advanced'
      fullPath: '/box-dice-advanced/'
      preLoaderRoute: typeof BoxDiceAdvancedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automated-system/': {
      id: '/automated-system/'
      path: '/automated-system'
      fullPath: '/automated-system/'
      preLoaderRoute: typeof AutomatedSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  AutomatedSystemIndexRoute: AutomatedSystemIndexRoute,
  BoxDiceAdvancedIndexRoute: BoxDiceAdvancedIndexRoute,
  BoxDiceIndexRoute: BoxDiceIndexRoute,
  BoxIndexRoute: BoxIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  FlowAdvancedIndexRoute: FlowAdvancedIndexRoute,
  FlowGraphIndexRoute: FlowGraphIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
