/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowGraphIndexRouteImport } from './routes/flow-graph/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as BoxIndexRouteImport } from './routes/box/index'
import { Route as AutomatedSystemIndexRouteImport } from './routes/automated-system/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowGraphIndexRoute = FlowGraphIndexRouteImport.update({
  id: '/flow-graph/',
  path: '/flow-graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxIndexRoute = BoxIndexRouteImport.update({
  id: '/box/',
  path: '/box/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatedSystemIndexRoute = AutomatedSystemIndexRouteImport.update({
  id: '/automated-system/',
  path: '/automated-system/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automated-system/': typeof AutomatedSystemIndexRoute
  '/box/': typeof BoxIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/flow-graph/': typeof FlowGraphIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automated-system': typeof AutomatedSystemIndexRoute
  '/box': typeof BoxIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/flow-graph': typeof FlowGraphIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automated-system/': typeof AutomatedSystemIndexRoute
  '/box/': typeof BoxIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/flow-graph/': typeof FlowGraphIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automated-system/'
    | '/box/'
    | '/components/'
    | '/flow-graph/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/automated-system' | '/box' | '/components' | '/flow-graph'
  id:
    | '__root__'
    | '/'
    | '/automated-system/'
    | '/box/'
    | '/components/'
    | '/flow-graph/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomatedSystemIndexRoute: typeof AutomatedSystemIndexRoute
  BoxIndexRoute: typeof BoxIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  FlowGraphIndexRoute: typeof FlowGraphIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-graph/': {
      id: '/flow-graph/'
      path: '/flow-graph'
      fullPath: '/flow-graph/'
      preLoaderRoute: typeof FlowGraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box/': {
      id: '/box/'
      path: '/box'
      fullPath: '/box/'
      preLoaderRoute: typeof BoxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automated-system/': {
      id: '/automated-system/'
      path: '/automated-system'
      fullPath: '/automated-system/'
      preLoaderRoute: typeof AutomatedSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomatedSystemIndexRoute: AutomatedSystemIndexRoute,
  BoxIndexRoute: BoxIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  FlowGraphIndexRoute: FlowGraphIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
