/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonIndexRouteImport } from './routes/person/index'
import { Route as FlowIndexRouteImport } from './routes/flow/index'
import { Route as FlowGraphIndexRouteImport } from './routes/flow-graph/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as BoxDiceIndexRouteImport } from './routes/box-dice/index'
import { Route as AutomatedSystemIndexRouteImport } from './routes/automated-system/index'
import { Route as AuthCertCallbackRouteImport } from './routes/auth.cert.callback'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIndexRoute = PersonIndexRouteImport.update({
  id: '/person/',
  path: '/person/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowIndexRoute = FlowIndexRouteImport.update({
  id: '/flow/',
  path: '/flow/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowGraphIndexRoute = FlowGraphIndexRouteImport.update({
  id: '/flow-graph/',
  path: '/flow-graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDiceIndexRoute = BoxDiceIndexRouteImport.update({
  id: '/box-dice/',
  path: '/box-dice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatedSystemIndexRoute = AutomatedSystemIndexRouteImport.update({
  id: '/automated-system/',
  path: '/automated-system/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCertCallbackRoute = AuthCertCallbackRouteImport.update({
  id: '/auth/cert/callback',
  path: '/auth/cert/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/automated-system/': typeof AutomatedSystemIndexRoute
  '/box-dice/': typeof BoxDiceIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/flow-graph/': typeof FlowGraphIndexRoute
  '/flow/': typeof FlowIndexRoute
  '/person/': typeof PersonIndexRoute
  '/auth/cert/callback': typeof AuthCertCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/automated-system': typeof AutomatedSystemIndexRoute
  '/box-dice': typeof BoxDiceIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/flow-graph': typeof FlowGraphIndexRoute
  '/flow': typeof FlowIndexRoute
  '/person': typeof PersonIndexRoute
  '/auth/cert/callback': typeof AuthCertCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/automated-system/': typeof AutomatedSystemIndexRoute
  '/box-dice/': typeof BoxDiceIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/flow-graph/': typeof FlowGraphIndexRoute
  '/flow/': typeof FlowIndexRoute
  '/person/': typeof PersonIndexRoute
  '/auth/cert/callback': typeof AuthCertCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/automated-system/'
    | '/box-dice/'
    | '/components/'
    | '/flow-graph/'
    | '/flow/'
    | '/person/'
    | '/auth/cert/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/automated-system'
    | '/box-dice'
    | '/components'
    | '/flow-graph'
    | '/flow'
    | '/person'
    | '/auth/cert/callback'
  id:
    | '__root__'
    | '/'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/automated-system/'
    | '/box-dice/'
    | '/components/'
    | '/flow-graph/'
    | '/flow/'
    | '/person/'
    | '/auth/cert/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AutomatedSystemIndexRoute: typeof AutomatedSystemIndexRoute
  BoxDiceIndexRoute: typeof BoxDiceIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  FlowGraphIndexRoute: typeof FlowGraphIndexRoute
  FlowIndexRoute: typeof FlowIndexRoute
  PersonIndexRoute: typeof PersonIndexRoute
  AuthCertCallbackRoute: typeof AuthCertCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/': {
      id: '/person/'
      path: '/person'
      fullPath: '/person/'
      preLoaderRoute: typeof PersonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/': {
      id: '/flow/'
      path: '/flow'
      fullPath: '/flow/'
      preLoaderRoute: typeof FlowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-graph/': {
      id: '/flow-graph/'
      path: '/flow-graph'
      fullPath: '/flow-graph/'
      preLoaderRoute: typeof FlowGraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-dice/': {
      id: '/box-dice/'
      path: '/box-dice'
      fullPath: '/box-dice/'
      preLoaderRoute: typeof BoxDiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automated-system/': {
      id: '/automated-system/'
      path: '/automated-system'
      fullPath: '/automated-system/'
      preLoaderRoute: typeof AutomatedSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cert/callback': {
      id: '/auth/cert/callback'
      path: '/auth/cert/callback'
      fullPath: '/auth/cert/callback'
      preLoaderRoute: typeof AuthCertCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AutomatedSystemIndexRoute: AutomatedSystemIndexRoute,
  BoxDiceIndexRoute: BoxDiceIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  FlowGraphIndexRoute: FlowGraphIndexRoute,
  FlowIndexRoute: FlowIndexRoute,
  PersonIndexRoute: PersonIndexRoute,
  AuthCertCallbackRoute: AuthCertCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
